### PR TITLE
All inline styles to external css added

### PR DESCRIPTION
**Pull request by divyaprakash-Rx**
All inline styles are now converted to external css. Please check.

### CODE REVIEW

**Comment by priyanshunayan** [comment]
Please put cache in gitignore and push the changes. Then we can review.

**Comment by divyaprakash-Rx** [comment]
It has already been deleted in this PR. Actually, in .gitignore, .cache is added and in this PR, I have deleted all those cache files.

**Comment by priyanshunayan** [comment]
> It has already been deleted in this PR. Actually, in .gitignore, .cache is added and in this PR, I have deleted all those cache files.

I am seeing 114 files changed in this PR, most of them are from .cache?

**Comment by divyaprakash-Rx** [comment]
> 
> 
> > It has already been deleted in this PR. Actually, in .gitignore, .cache is added and in this PR, I have deleted all those cache files.
> 
> I am seeing 114 files changed in this PR, most of them are from .cache?

Yes, they are the files which are deleted, previously which was present in .cache .

**Comment by priyanshunayan** [comment]
Ah! my bad. 😂

**Pull request merged**
